### ISSUE TITLE
Content Admin doesn't get permissions for Basic Page content type

### ISSUE THREAD

**Issue by jenitehan** [jenitehan/tasty_backend#10]
I recently removed the content admin permissions being set for the Basic Page content type in the TB Base module.  But now when running the install profile the content admin role doesn't have permissions for that content type.  Those permissions can't be in TB Base module since that might be added to sites that don't have a Basic Page content type.

Maybe the whole basic page content type and permissions should be in a separate module.

**Comment by dbazuin** [comment]
Why not check it the content type exist before adding the permission?

**Comment by jenitehan** [comment]
I'm inclined to agree with you, but I still think I'm going to separate it out into a sub-module.  I don't really want the Tasty Backend Base module to assume anything about where it's being installed, from the TB profile or into an existing site.  So even checking if the content type exists in that module doesn't seem like a good idea.

At this point I'm planning on breaking out the Basic Page content type into it's own submodule.  Then it can be included in the Tasty Backend install profile without any problems, or dropped into a site that already has the Basic Page content type, or doesn't.

In that module I'll do the checking if the content type exists.  If it doesn't the module will create it then assign the correct permissions for the content admin role.  If it does exist it will skip creation but still apply the permissions.

**Comment by jenitehan** [comment]
I've added a new Tasty Backend Page module which has been added to the make file in the install profile.

https://github.com/jenitehan/tasty_backend_page
