### ISSUE TITLE
Drupal 8 Tasty Backend

### ISSUE THREAD

**Issue by frederickjh** [jenitehan/tasty_backend#14]
Hi! 
Just wondering if you have started work or research on a Tasty Backed for Drupal 8.

Thanks again for the Tasty Backend project.
Frederick

**Comment by jenitehan** [comment]
Hiya, I've got a few ideas but haven't really begun and work yet on a D8 tasty backend.  I've got a couple of D8 projects starting in the new year, so hopefully I can get some preliminary stuff put together while working on those.

**Comment by frederickjh** [comment]
@jenitehan Here is what I have so far. It gets rid of the right sidebar and puts it in vertical tabs, but a separate group of vertical tabs. This code goes in your `admin_theme_name.theme` file.

Change instances of **admin_theme_name** to your admin theme in the code below. 

``` php
<?php

/**
 * @file
 * Functions to support theming in the Admin theme.
 */
 
use Drupal\Core\Form\FormStateInterface;
 /**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\node\NodeForm.
 *
 * Changes vertical tabs to container and adds meta information.
 */
 function admin_theme_name_theme_form_node_form_alter(&$form, FormStateInterface $form_state) { 
  /** @var \Drupal\node\NodeInterface $node */
  $node = $form_state->getFormObject()->getEntity();

  $form['#theme'] = array('node_edit_form');
  $form['#attached']['library'][] = 'admin_theme_name/node-form';
  $form['advanced']['#type'] = 'vertical_tabs';
  $form['revision_information']['#type'] = 'vertical_tabs';
}
```
This may not be solvable until this [d.o](http://drupal.org) Field Groups issue is solved:

[Allow to position the group in the advanced (sidebar) column](https://www.drupal.org/node/2652642)

which is related to this Drupal 8 core issue:

[Replace hook_form_node_form_alter() implementations with configured field layouts](https://www.drupal.org/node/2845425https://www.drupal.org/node/2845425)

Which is posponed until another Drupal 8 core issue is solved:

[#2834025: Remove @internal from Layout classes when stable](https://www.drupal.org/node/2845425) (Not following this issue.)
